### ISSUE TITLE
How to issue orml tokens?

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#146]
## Issue summary

It seems that we can only spend but not issue orml tokens in pallet asset_index for now.

Maybe we should 

* issue currency first
* and then transfer it to the treasury 

In `asset-index`

Or we have to develop a new call for issuing currencies.

## Other information and links
-

**Comment by mattsse** [comment]
is this solved with #139 modified chain spec?

**Comment by clearloop** [comment]
> is this solved with #139 modified chain spec?

Not yet...I just mocked some testing orml tokens in `chain_spec` but we still don't have functions to issue them =.=

**Comment by mattsse** [comment]
Liquid assets are supposed to get issued once an xcm arrives that deposits them in an user account PINT.
SAFTs are minted in the saft registry upon a gov proposal.

**Comment by clearloop** [comment]
> Liquid assets are supposed to get issued once an xcm arrives that deposits them in an user account PINT.
> SAFTs are minted in the saft registry upon a gov proposal.
> Perhaps it makes sense to add an option to mint assets for testnet?

The root case of this issue is here

https://github.com/ChainSafe/PINT/blob/a9b2f8fcd7dca14e2f2a88beb9c6e9d90008b3a7/pallets/asset-index/src/lib.rs#L641

Whatever mint Liquid or SAFTs, we should mint `Currency` which is orml token as well, so it can transfer otherwise will fire `Balance is too low` like errors

**Comment by mattsse** [comment]
> > Liquid assets are supposed to get issued once an xcm arrives that deposits them in an user account PINT.
> > SAFTs are minted in the saft registry upon a gov proposal.
> 
> The root case of this issue is here
> 
> https://github.com/ChainSafe/PINT/blob/a9b2f8fcd7dca14e2f2a88beb9c6e9d90008b3a7/pallets/asset-index/src/lib.rs#L641
> 
> Whatever mint Liquid or SAFTs, we should mint `Currency` which is orml token as well, so it can transfer otherwise will fire `Balance is too low` like errors
> 
> > Perhaps it makes sense to add an option to mint assets for testnet?
> 
> Agree with this, we can wrap some `sudo` calls for theses

Can you elaborate on the scenario when this error is thrown? `transfer` will obviously only work if the account is funded and can get to zero, so no existential deposits for assets.

**Comment by clearloop** [comment]
> Can you elaborate on the scenario when this error is thrown? 

For example, without initial ORML tokens for account Account, we `add_asset(42_CurrencyId)` use `Alice`, this transfer will be failed, because Alice doesn't have ORML tokens of `42_CurrencyId`

**Comment by mattsse** [comment]
I see,
so the ORML tokens pallet is merely used for tracking all the balances of various assets, whereas the `asset-index` and `saft-registry` track what assets are supported.

I think the confusion comes again from the naming of `add_asset`, which intended functionality is: transferring x units of an asset from the user account into the treasury in exchange for the given amount of PINT token that get minted into the user's account. So `add_asset` means adding existing assets to the index in exchange for PINT.

Does this clear things up a bit?

**Comment by clearloop** [comment]
> so the ORML tokens pallet is merely used for tracking all the balances of various assets

Should we issue ORML tokens in Genesis? If not, where should they from? 

As it is only for tracking assets, we might need to mint them along with we minting `Liquid/Asset`, but not minting them in Genesis?

**Comment by mattsse** [comment]
> > so the ORML tokens pallet is merely used for tracking all the balances of various assets
> 
> Should we issue ORML tokens in Genesis? If not, where should they from?
> 
> As it is only for tracking assets, we might need to mint/burn them along with minting/burning `Liquid/Asset`, but not operating them in Genesis?

I've thought about this and there are some things we need to keep in mind.
Since the indextoken represents the contributed assets, and the initial balance of liquid/saft is zero. the index token balance should also be zero.
however this introduces a couple of problems, mainly:
* If there are no funds, how to pay for transactions?
* How to pay for transactions, Index token and/or assets?
* should fees be paid in SAFT?

**Comment by mattsse** [comment]
from the technical doc: Some PINT will be included in genesis, other assets will be contributed via governance proposals.
Voting to close this @clearloop

**Comment by clearloop** [comment]
Should we open another issue for checking this config?

**Comment by mattsse** [comment]
Maybe we add a point to #238 instead? or a new tracking item for Launch/runtime config or something?
